"use client";
import Head from "next/head";
import Header from "../components/Header/Header";
import "./globals.css";

import { Amplify } from "aws-amplify";
import awsExports from "../aws-exports";
Amplify.configure(awsExports);
// import { Poppins } from "next/font/google";

// const pooppins = Poppins({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          crossOrigin="anonymous"
        />
      </Head>
      <body>
        {/* <body className={pooppins.className}> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
