import Header from "../components/Header/Header";
import "./globals.css";
// import { Poppins } from "next/font/google";

// const pooppins = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        {/* <body className={pooppins.className}> */}
        <Header />
        {children}
      </body>
    </html>
  );
}
