"use client";
import Head from "next/head";
import Header from "../components/Header/Header";
import "./globals.css";

import { Amplify } from "aws-amplify";
import awsExports from "../aws-exports";
import GlobalContext from "@/contexts/GlobalContext";
import { useEffect, useState } from "react";
import Footer from "@/components/Footer/Footer";
Amplify.configure(awsExports);
// import { Poppins } from "next/font/google";

// const pooppins = Poppins({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [globals, setGlobals] = useState({
    openCartDrawer: false,
    openSideBar: false,
    cartItems: [],
  });
  useEffect(() => {
    const carritoLs = JSON.parse(localStorage.getItem("carrito")) ?? [];
    setGlobals({ ...globals, cartItems: carritoLs });
  }, []);
  useEffect(() => {
    localStorage.setItem("carrito", JSON.stringify(globals.cartItems));
  }, [globals.cartItems]);

  return (
    <html lang="en">
      <Head>
        <title>Pharmahogar | Encuentra tu medicamento</title>
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
          crossOrigin="anonymous"
        />
      </Head>
      <GlobalContext.Provider value={{ globals, setGlobals }}>
        <body>
          {/* <body className={pooppins.className}> */}
          <Header />
          {children}
          <Footer />
        </body>
      </GlobalContext.Provider>
    </html>
  );
}
